### ISSUE TITLE
Error getting lists

### ISSUE THREAD

**Issue by dkoukoul** [Twilight0/plugin.video.ert.gr#4]
Using Kodi 18.8 on Libreelec 9.2.5 on Pi4. Plug in installed and it shows the first list (Movies, Tv Series) but when trying to retrieve the list of content it throws an error. this is from the logs

`ERROR:   File "/storage/.kodi/addons/script.module.tulip/lib/tulip/client.py", line 173, in request
2019-04-11 17:01:44.692 T:2449531760   ERROR:     response = urllib2.urlopen(req, timeout=int(timeout))
2019-04-11 17:01:44.692 T:2449531760   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
2019-04-11 17:01:44.692 T:2449531760   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 429, in open
2019-04-11 17:01:44.692 T:2449531760   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
2019-04-11 17:01:44.692 T:2449531760   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
2019-04-11 17:01:44.692 T:2449531760   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
2019-04-11 17:01:44.693 T:2449531760   ERROR:   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
2019-04-11 17:01:44.695 T:2449531760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/addon.py", line 61, in <module>
                                                ert.Indexer().listing(url)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/ert.py", line 492, in listing
                                                self.list = self._listing(url)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/ert.py", line 410, in _listing
                                                ajax1 = json.loads(re.search(r'var loadmore_params = ({.+})', ajaxes[-1]).group(1))
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2019-04-11 17:01:44.713 T:2983187312  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
2019-04-11 17:01:44.799 T:2457924464   ERROR: GetDirectory - Error getting plugin://plugin.video.ert.gr/?action=listing&title=Movies&url=https%3a%2f%2fwww.ertflix.gr%2fcategory%2ftainies%2f
2019-04-11 17:01:44.812 T:3011993616   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ert.gr/?action=listing&title=Movies&url=https%3a%2f%2fwww.ertflix.gr%2fcategory%2ftainies%2f) failed`

**Comment by Twilight0** [comment]
Check version 3.0.5, it has just been uploaded, and let me know.

**Comment by dkoukoul** [comment]
It works, great work thanks!
