### ISSUE TITLE
Error getting list of kids content

### ISSUE THREAD

**Issue by bilias** [Twilight0/plugin.video.ert.gr#6]
version 3.2.0 on libreelec.
I believe (not sure) stopped working after updating to 3.2.0

You click on an kid's show (entertainment) and does not show the episode list.
It lists the shows but not the episodes.

Rest of content if browsed fine (and played)

2021-01-24 18:16:08.049 T:3012067344   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ert.gr/?action=play&url=https%3A%2F%2Fwww.ertflix.gr%2Fpedika%2Ffloypaloy%2F&title=%CE%A6%CE%BB%CE%BF%CF%85%CF%80%CE%B1%CE%BB%CE%BF%CF%8D&image=https%3A%2F%2Fwww.ertflix.gr%2Fwp-content%2Fuploads%2F2020%2F09%2Ffloopaloo-1280-565x318.jpg&plot=%28K%29+%E2%80%93+%CE%9A%CE%B9%CE%BD%CE%BF%CF%8D%CE%BC%CE%B5%CE%BD%CE%B1+%CF%83%CF%87%CE%AD%CE%B4%CE%B9%CE%B1%5BCR%5D%CE%97+%CE%BA%CE%B1%CE%B8%CE%B7%CE%BC%CE%B5%CF%81%CE%B9%CE%BD%CF%8C%CF%84%CE%B7%CF%84%CE%B1+%CF%84%CE%B7%CF%82+%CE%9B%CE%AF%CE%B6%CE%B1%CF%82+%CE%BA%CE%B1%CE%B9+%CF%84%CE%BF%CF%85+%CE%9C%CE%B1%CF%84+%CF%83%CF%84%CE%B7%CE%BD+%CE%BA%CE%B1%CF%84%CE%B1%CF%83%CE%BA%CE%AE%CE%BD%CF%89%CF%83%CE%B7+%CE%BA%CE%AC%CE%B8%CE%B5+%CE%AC%CE%BB%CE%BB%CE%BF+%CF%80%CE%B1%CF%81%CE%AC+%CE%B2%CE%B1%CF%81%CE%B5%CF%84%CE%AE+%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9.%0A%CE%9F%CE%B9+%CF%83%CE%BA%CE%B7%CE%BD%CE%AD%CF%82+%CF%84%CE%BF%CF%85%CF%82+%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9+%CF%83%CF%84%CE%B7%CE%BC%CE%AD%CE%BD%CE%B5%CF%82+%CF%83%CE%B5+%CE%AD%CE%BD%CE%B1+%CE%B4%CE%AC%CF%83%CE%BF%CF%82+%CE%B3%CE%B5%CE%BC%CE%AC%CF%84%CE%BF+%CE%BC%CF%85%CF%83%CF%84%CE%B9%CE%BA%CE%AC+%CF%80%CE%BF%CF%85+%CE%BC%CF%8C%CE%BD%CE%BF+%CF%84%CE%BF+%CE%A6%CE%BB%CE%BF%CF%85%CF%80%CE%B1%CE%BB%CE%BF%CF%8D+%CE%B3%CE%BD%CF%89%CF%81%CE%AF%CE%B6%CE%B5%CE%B9+%CE%BA%CE%B1%CE%B9+%CF%80%CF%81%CE%BF%CF%83%CF%84%CE%B1%CF%84%CE%B5%CF%8D%CE%B5%CE%B9.%0A%CE%9F+%CF%86%CF%8D%CE%BB%CE%B1%CE%BA%CE%B1%CF%82-%CE%AC%CE%B3%CE%B3%CE%B5%CE%BB%CE%BF%CF%82+%CF%84%CE%B7%CF%82+%CE%A6%CF%8D%CF%83%CE%B7%CF%82%2C+%CE%B1%CE%BD+%CE%BA%CE%B1%CE%B9+%CE%B1%CF%8C%CF%81%CE%B1%CF%84%CE%BF%CF%82%2C+%C2%AB%CF%83%CF%85%CE%BD%CE%BF%CE%BC%CE%B9%CE%BB%CE%B5%CE%AF%C2%BB+%CE%BA%CE%B1%CE%B8%CE%B7%CE%BC%CE%B5%CF%81%CE%B9%CE%BD%CE%AC+%CE%BC%CE%B5+%CF%84%CE%B1+%CE%B4%CF%8D%CE%BF+%CE%BE%CE%B1%CE%B4%CE%AD%CE%BB%CF%86%CE%B9%CE%B1+%CE%BA%CE%B1%CE%B9+%CF%84%CE%BF%CF%85%CF%82+%CF%86%CE%AF%CE%BB%CE%BF%CF%85%CF%82+%CF%84%CE%BF%CF%85%CF%82%2C+%CF%80%CE%BF%CF%85+%CE%BC%CE%B1%CE%BA%CF%81%CE%B9%CE%AC+%CE%B1%CF%80%CF%8C+%CF%84%CE%B1+%CE%B1%CE%B4%CE%B9%CE%AC%CE%BA%CF%81%CE%B9%CF%84%CE%B1+%CE%BC%CE%AC%CF%84%CE%B9%CE%B1+%CF%84%CF%89%CE%BD+%CE%BC%CE%B5%CE%B3%CE%AC%CE%BB%CF%89%CE%BD%2C+%CF%88%CE%AC%CF%87%CE%BD%CE%BF%CF%85%CE%BD+%CE%B1%CF%80%CE%B5%CE%B3%CE%BD%CF%89%CF%83%CE%BC%CE%AD%CE%BD%CE%B1+%CE%BD%CE%B1+%CF%84%CE%BF%CE%BD+%CE%B2%CF%81%CE%BF%CF%85%CE%BD+%CE%BA%CE%B1%CE%B9+%CE%BD%CE%B1+%CF%84%CE%BF%CE%BD+%CE%B4%CE%BF%CF%85%CE%BD+%CE%B1%CF%80%CF%8C+%CE%BA%CE%BF%CE%BD%CF%84%CE%AC.%0A%CE%98%CE%B1+%CE%B1%CE%BD%CE%B1%CE%BA%CE%B1%CE%BB%CF%8D%CF%88%CE%BF%CF%85%CE%BD+%CE%AC%CF%81%CE%B1%CE%B3%CE%B5+%CF%80%CE%BF%CF%84%CE%AD+%CF%80%CE%BF%CF%8D+%CE%BA%CF%81%CF%8D%CE%B2%CE%B5%CF%84%CE%B1%CE%B9+%CF%84%CE%BF+%CE%A6%CE%BB%CE%BF%CF%85%CF%80%CE%B1%CE%BB%CE%BF%CF%8D%3B]
2021-01-24 18:16:08.576 T:2870690672   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://mirrors.kodi.tv/addons/leia/plugin.video.tv3.cat/icon.png
2021-01-24 18:16:10.219 T:3012067344 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2021-01-24 18:16:28.879 T:2794713968 WARNING: Previous line repeats 6 times.
2021-01-24 18:16:28.879 T:2794713968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/addon.py", line 82, in <module>
                                                ert.Indexer().play(url)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/ert.py", line 625, in play
                                                stream = self.resolve(url)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/ert.py", line 823, in resolve
                                                iframe = parseDOM(html, 'iframe', ret='src')[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

2021-01-24 18:16:29.036 T:3012067344   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ert.gr/?action=play&url=https%3A%2F%2Fwww.ertflix.gr%2Fpedika%2Ffloypaloy%2F&title=%CE%A6%CE%BB%CE%BF%CF%85%CF%80%CE%B1%CE%BB%CE%BF%CF%8D&image=https%3A%2F%2Fwww.ertflix.gr%2Fwp-content%2Fuploads%2F2020%2F09%2Ffloopaloo-1280-565x318.jpg&plot=%28K%29+%E2%80%93+%CE%9A%CE%B9%CE%BD%CE%BF%CF%8D%CE%BC%CE%B5%CE%BD%CE%B1+%CF%83%CF%87%CE%AD%CE%B4%CE%B9%CE%B1%5BCR%5D%CE%97+%CE%BA%CE%B1%CE%B8%CE%B7%CE%BC%CE%B5%CF%81%CE%B9%CE%BD%CF%8C%CF%84%CE%B7%CF%84%CE%B1+%CF%84%CE%B7%CF%82+%CE%9B%CE%AF%CE%B6%CE%B1%CF%82+%CE%BA%CE%B1%CE%B9+%CF%84%CE%BF%CF%85+%CE%9C%CE%B1%CF%84+%CF%83%CF%84%CE%B7%CE%BD+%CE%BA%CE%B1%CF%84%CE%B1%CF%83%CE%BA%CE%AE%CE%BD%CF%89%CF%83%CE%B7+%CE%BA%CE%AC%CE%B8%CE%B5+%CE%AC%CE%BB%CE%BB%CE%BF+%CF%80%CE%B1%CF%81%CE%AC+%CE%B2%CE%B1%CF%81%CE%B5%CF%84%CE%AE+%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9.%0A%CE%9F%CE%B9+%CF%83%CE%BA%CE%B7%CE%BD%CE%AD%CF%82+%CF%84%CE%BF%CF%85%CF%82+%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9+%CF%83%CF%84%CE%B7%CE%BC%CE%AD%CE%BD%CE%B5%CF%82+%CF%83%CE%B5+%CE%AD%CE%BD%CE%B1+%CE%B4%CE%AC%CF%83%CE%BF%CF%82+%CE%B3%CE%B5%CE%BC%CE%AC%CF%84%CE%BF+%CE%BC%CF%85%CF%83%CF%84%CE%B9%CE%BA%CE%AC+%CF%80%CE%BF%CF%85+%CE%BC%CF%8C%CE%BD%CE%BF+%CF%84%CE%BF+%CE%A6%CE%BB%CE%BF%CF%85%CF%80%CE%B1%CE%BB%CE%BF%CF%8D+%CE%B3%CE%BD%CF%89%CF%81%CE%AF%CE%B6%CE%B5%CE%B9+%CE%BA%CE%B1%CE%B9+%CF%80%CF%81%CE%BF%CF%83%CF%84%CE%B1%CF%84%CE%B5%CF%8D%CE%B5%CE%B9.%0A%CE%9F+%CF%86%CF%8D%CE%BB%CE%B1%CE%BA%CE%B1%CF%82-%CE%AC%CE%B3%CE%B3%CE%B5%CE%BB%CE%BF%CF%82+%CF%84%CE%B7%CF%82+%CE%A6%CF%8D%CF%83%CE%B7%CF%82%2C+%CE%B1%CE%BD+%CE%BA%CE%B1%CE%B9+%CE%B1%CF%8C%CF%81%CE%B1%CF%84%CE%BF%CF%82%2C+%C2%AB%CF%83%CF%85%CE%BD%CE%BF%CE%BC%CE%B9%CE%BB%CE%B5%CE%AF%C2%BB+%CE%BA%CE%B1%CE%B8%CE%B7%CE%BC%CE%B5%CF%81%CE%B9%CE%BD%CE%AC+%CE%BC%CE%B5+%CF%84%CE%B1+%CE%B4%CF%8D%CE%BF+%CE%BE%CE%B1%CE%B4%CE%AD%CE%BB%CF%86%CE%B9%CE%B1+%CE%BA%CE%B1%CE%B9+%CF%84%CE%BF%CF%85%CF%82+%CF%86%CE%AF%CE%BB%CE%BF%CF%85%CF%82+%CF%84%CE%BF%CF%85%CF%82%2C+%CF%80%CE%BF%CF%85+%CE%BC%CE%B1%CE%BA%CF%81%CE%B9%CE%AC+%CE%B1%CF%80%CF%8C+%CF%84%CE%B1+%CE%B1%CE%B4%CE%B9%CE%AC%CE%BA%CF%81%CE%B9%CF%84%CE%B1+%CE%BC%CE%AC%CF%84%CE%B9%CE%B1+%CF%84%CF%89%CE%BD+%CE%BC%CE%B5%CE%B3%CE%AC%CE%BB%CF%89%CE%BD%2C+%CF%88%CE%AC%CF%87%CE%BD%CE%BF%CF%85%CE%BD+%CE%B1%CF%80%CE%B5%CE%B3%CE%BD%CF%89%CF%83%CE%BC%CE%AD%CE%BD%CE%B1+%CE%BD%CE%B1+%CF%84%CE%BF%CE%BD+%CE%B2%CF%81%CE%BF%CF%85%CE%BD+%CE%BA%CE%B1%CE%B9+%CE%BD%CE%B1+%CF%84%CE%BF%CE%BD+%CE%B4%CE%BF%CF%85%CE%BD+%CE%B1%CF%80%CF%8C+%CE%BA%CE%BF%CE%BD%CF%84%CE%AC.%0A%CE%98%CE%B1+%CE%B1%CE%BD%CE%B1%CE%BA%CE%B1%CE%BB%CF%8D%CF%88%CE%BF%CF%85%CE%BD+%CE%AC%CF%81%CE%B1%CE%B3%CE%B5+%CF%80%CE%BF%CF%84%CE%AD+%CF%80%CE%BF%CF%8D+%CE%BA%CF%81%CF%8D%CE%B2%CE%B5%CF%84%CE%B1%CE%B9+%CF%84%CE%BF+%CE%A6%CE%BB%CE%BF%CF%85%CF%80%CE%B1%CE%BB%CE%BF%CF%8D%3B]
2021-01-24 18:16:36.385 T:3012067344 WARNING: CGUIWindowManager - HandleAction - ignoring action 92, because topmost modal dialog closing animation is running
2021-01-24 18:16:39.349 T:2862297968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/addon.py", line 82, in <module>
                                                ert.Indexer().play(url)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/ert.py", line 625, in play
                                                stream = self.resolve(url)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/ert.py", line 823, in resolve
                                                iframe = parseDOM(html, 'iframe', ret='src')[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2021-01-24 18:16:39.504 T:3012067344   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ert.gr/?action=play&url=https%3A%2F%2Fwww.ertflix.gr%2Fpedika%2Fan-imoyn%2F&title=%CE%91%CE%BD+%CE%AE%CE%BC%CE%BF%CF%85%CE%BD...&image=https%3A%2F%2Fwww.ertflix.gr%2Fwp-content%2Fuploads%2F2020%2F12%2FIf-I-were-an-Animal-1280X720-img-565x318.jpg&plot=%CE%A3%CE%B5%CE%B9%CF%81%CE%AC+52+%CF%80%CE%B5%CE%BD%CF%84%CE%AC%CE%BB%CE%B5%CF%80%CF%84%CF%89%CE%BD+%CE%BD%CF%84%CE%BF%CE%BA%CE%B9%CE%BC%CE%B1%CE%BD%CF%84%CE%AD%CF%81%2C+%CF%80%CE%B1%CF%81%CE%B1%CE%B3%CF%89%CE%B3%CE%AE%CF%82+%CE%93%CE%B1%CE%BB%CE%BB%CE%AF%CE%B1%CF%82+2018.%5BCR%5D%CE%97+%CE%95%CE%BC%CE%B1+%CE%B5%CE%AF%CE%BD%CE%B1%CE%B9+%CE%AD%CE%BE%CE%B9+%CE%B5%CF%84%CF%8E%CE%BD.+%CE%9F+%CE%A4%CE%B9%CE%BC+%CE%B5%CE%BD%CE%BD%CE%AD%CE%B1.%0A%CE%A4%CE%B1+%CE%B4%CF%8D%CE%BF+%CE%B1%CE%B4%CE%AD%CE%BB%CF%86%CE%B9%CE%B1+%CE%BC%CE%B5%CE%B3%CE%B1%CE%BB%CF%8E%CE%BD%CE%BF%CF%85%CE%BD+%CE%BC%CE%B1%CE%B6%CE%AF+%CE%BC%CE%B5+%CF%84%CE%B1+%CE%B1%CE%B3%CE%B1%CF%80%CE%B7%CE%BC%CE%AD%CE%BD%CE%B1+%CF%84%CE%BF%CF%85%CF%82+%CE%B6%CF%8E%CE%B1+%CE%BA%CE%B1%CE%B9+%CE%B1%CF%86%CE%B7%CE%B3%CE%BF%CF%8D%CE%BD%CF%84%CE%B1%CE%B9+%CF%84%CE%B7+%CE%B6%CF%89%CE%AE+%CF%84%CE%BF%CF%85%CF%82%2C+%CE%B1%CF%80%CF%8C+%CF%84%CE%B7+%CE%B3%CE%AD%CE%BD%CE%BD%CE%B7%CF%83%CE%B7+%CE%BC%CE%AD%CF%87%CF%81%CE%B9+%CF%84%CE%B7%CE%BD+%CE%B5%CE%BD%CE%B7%CE%BB%CE%B9%CE%BA%CE%AF%CF%89%CF%83%CE%B7.%0A%CE%A4%CE%B1+%CF%80%CF%81%CF%8E%CF%84%CE%B1+%CE%B2%CE%AE%CE%BC%CE%B1%CF%84%CE%B1%2C+%CF%84%CE%B1+%CF%80%CF%81%CF%8E%CF%84%CE%B1+%CE%B3%CE%B5%CF%8D%CE%BC%CE%B1%CF%84%CE%B1%2C+%CE%BF%CE%B9+%CF%80%CF%81%CF%8E%CF%84%CE%B5%CF%82+%CE%B2%CF%8C%CE%BB%CF%84%CE%B5%CF%82+%CE%AD%CE%BE%CF%89+%CE%B1%CF%80%CF%8C+%CF%84%CE%B7+%CF%86%CF%89%CE%BB%CE%B9%CE%AC+%CE%BA%CE%B1%CE%B9+%CE%B7+%CE%BC%CE%B5%CE%B3%CE%AC%CE%BB%CE%B7+%CF%83%CF%84%CE%B9%CE%B3%CE%BC%CE%AE+%CF%84%CE%B7%CF%82+%CE%B5%CE%BB%CE%B5%CF%85%CE%B8%CE%B5%CF%81%CE%AF%CE%B1%CF%82%2C+%CF%8C%CF%80%CE%BF%CF%85+%CF%84%CE%B1+%CE%B6%CF%8E%CE%B1+%CF%80%CE%BB%CE%AD%CE%BF%CE%BD+%CE%B8%CE%B1+%CF%83%CF%85%CE%BD%CE%B5%CF%87%CE%AF%CF%83%CE%BF%CF%85%CE%BD+%CE%BC%CF%8C%CE%BD%CE%B1+%CF%84%CE%BF%CF%85%CF%82+%CF%83%CF%84%CE%B7+%CE%B6%CF%89%CE%AE.%0A%CE%A4%CE%B1+%CF%80%CE%B1%CE%B9%CE%B4%CE%B9%CE%AC+%CE%B2%CE%BB%CE%AD%CF%80%CE%BF%CF%85%CE%BD+%CE%BC%CE%B5+%CF%84%CE%B1+%CE%AF%CE%B4%CE%B9%CE%B1+%CF%84%CE%BF%CF%85%CF%82+%CF%84%CE%B1+%CE%BC%CE%AC%CF%84%CE%B9%CE%B1+%CF%84%CE%B9%CF%82+%CE%BC%CE%B5%CE%B3%CE%AC%CE%BB%CE%B5%CF%82+%CE%B1%CE%BB%CE%BB%CE%B1%CE%B3%CE%AD%CF%82+%CE%BA%CE%B1%CE%B9+%CF%84%CE%B1+%CE%B1%CE%BD%CE%B1%CF%80%CF%84%CF%85%CE%BE%CE%B9%CE%B1%CE%BA%CE%AC+%CE%BF%CF%81%CF%8C%CF%83%CE%B7%CE%BC%CE%B1+%CF%80%CE%BF%CF%85+%CF%80%CE%B5%CF%81%CE%BD%CE%AC+%CE%AD%CE%BD%CE%B1+%CE%B6%CF%8E%CE%BF+%CE%BC%CE%AD%CF%87%CF%81%CE%B9+%CE%BD%CE%B1+%CE%BC%CE%B5%CE%B3%CE%B1%CE%BB%CF%8E%CF%83%CE%B5%CE%B9+%CE%BA%CE%B9+%CE%AD%CF%84%CF%83%CE%B9+%CE%BA%CE%B1%CF%84%CE%B1%CE%BB%CE%B1%CE%B2%CE%B1%CE%AF%CE%BD%CE%BF%CF%85%CE%BD+%CE%BA%CE%B1%CE%B9+%CF%84%CE%B7+%CE%B4%CE%B9%CE%BA%CE%AE+%CF%84%CE%BF%CF%85%CF%82+%CE%B1%CE%BD%CE%AC%CF%80%CF%84%CF%85%CE%BE%CE%B7%2C+%CE%B1%CE%BB%CE%BB%CE%AC+%CE%BA%CE%B1%CE%B9+%CF%80%CF%8E%CF%82+%CE%BB%CE%B5%CE%B9%CF%84%CE%BF%CF%85%CF%81%CE%B3%CE%B5%CE%AF+%CE%BF+%CE%BA%CF%8D%CE%BA%CE%BB%CE%BF%CF%82+%CF%84%CE%B7%CF%82+%CE%B6%CF%89%CE%AE%CF%82+%CF%83%CF%84%CE%B7+%CF%86%CF%8D%CF%83%CE%B7.]
2021-01-24 18:16:56.409 T:2870690672   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)

**Comment by Twilight0** [comment]
I am aware of this issue, will fix it when I have time.

**Comment by Twilight0** [comment]
Problem fixed in 3.2.1.

**Comment by bilias** [comment]
works.
thanks :)
